version: "3.9"

services:
  backend:
    build: ./backend
    container_name: hackapel-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    # Optional for dev: live code changes from host
    volumes:
      - ./backend:/app
      - /app/node_modules
